/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_identity_pool_id:
    "ap-south-1:3ca888e8-c4fd-4f45-be56-e5447708ac67",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_4k4VPc77D",
  aws_user_pools_web_client_id: "1uidiet7uovq16r14jog74d4ka",
  oauth: {
    domain:
      "socialproviderb5dd7868-b5dd7868-dev.auth.ap-south-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://main.d2b65wp3mxn1jy.amplifyapp.com/register/",
    redirectSignOut: "https://main.d2b65wp3mxn1jy.amplifyapp.com/forget/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["EMAIL", "PHONE_NUMBER"],
  aws_cognito_social_providers: ["FACEBOOK", "GOOGLE", "AMAZON"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
